Ruby Group Capstone Project - Catalogue of things
Uzair-Manzoor/RubyCapstone pull request #42
Opened 2023-12-01 17:44 UTC by Uzair-Manzoor

### We are a team of 3 participants working on this project;
@ismayito 
@Ayokunnumi1 
@Uzair-Manzoor 

## This pull request has been created against the below mentioned implementations into the project as per project requirements:

1. Created the Item class in a separate .rb file, defining properties as required, except for 1-to-many relationships.
2. Implemented the methods can_be_archived?() and move_to_archive() in the Item class.
3. Created the main.rb file as the console app entry-point and implemented the startup actions for user interaction.
4. Created the Book class in a separate .rb file.
5. Created the Label class with an association to the Item class.
6. Defined properties for Book and Label classes in the constructor.
7. Implemented the add_item method in the Label class and overrode can_be_archived?() in the Book class.
8. Added unit tests for implemented methods.
9. Provided options for listing all books, labels, and adding a book.
10. Created a schema.sql file for the books and labels tables.
11. Created the MusicAlbum class in a separate .rb file.
12. Created the Genre class with an association to the Item class.
13. Defined properties for MusicAlbum and Genre classes in the constructor.
14. Implemented the add_item method in the Genre class and overrode can_be_archived?() in the MusicAlbum class.
15. Added unit tests for implemented methods.
16. Provided options for listing all music albums, genres, and adding a music album.
17. Created a schema.sql file for the music_albums and genres tables.
18. Created the Game class in a separate .rb file.
19. Created the Author class with an association to the Item class.
20. Defined properties for Game and Author classes in the constructor.
21. Implemented the add_item method in the Author class and overrode can_be_archived?
     () in the Game class.
22. Added unit tests for implemented methods.
23. Provided options for listing games, authors, and adding a game.
24. Saved data to .json files.
25. Created a schema.sql file for the games and authors tables.
26. Recorded a presentation [Zoom](https://drive.google.com/file/d/1IcTH_GTSqDpVecmrXgxGk5VzPML29w6J/view?usp=sharing) video.

2023-12-01 20:13 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi Team,

### Nice job, you are almost there.

![giphy (2)](https://user-images.githubusercontent.com/68796232/223284713-d4ea97f0-5ad2-438b-8ac5-1481a991da3f.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [x] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- [x] Please check the inline comments below ⬇️.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-12-01 20:13 UTC, omar-muhamad commented on schema.sql
> +    PUBLISH_DATE DATE,
- [x] the `music_album` table should have only 2 columns `on_spotify` and `id`(which is referencing the item id). Please fix that to match the given [UML diagram](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/images/catalog_of_my_things.png)

![image](https://github.com/Uzair-Manzoor/RubyCapstone/assets/68796232/3eaa1487-121b-471e-9888-4d7941512265)

```suggestion
CREATE TABLE music_album(
	id INT NOT NULL,
	on_spotify BOOLEAN,
	FOREIGN KEY (id) REFERENCES item (id)
);
```

2023-12-01 20:13 UTC, omar-muhamad commented on schema.sql
> +  FOREIGN KEY (author_id) REFERENCES authors (id)
- [x] The `games` table should have only 3 columns `multiplayer`, `last_played_at`, and `id`(which is referencing the item id). Please fix that to match the given [UML diagram](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/images/catalog_of_my_things.png)

![image](https://github.com/Uzair-Manzoor/RubyCapstone/assets/68796232/7a97864a-b8a1-4c37-b2a5-ee34ba6c234c)

```suggestion
CREATE TABLE game(
	id INT NOT NULL,
	multiplayer BOOLEAN,
	last_played_at DATE,
	FOREIGN KEY (id) REFERENCES item (id)
);
```

2023-12-02 07:21 UTC, Whoistolu commented on README.md
> +- **[Video Presentation](https://drive.google.com/file/d/1IcTH_GTSqDpVecmrXgxGk5VzPML29w6J/view)**
- Well resolved team

2023-12-02 07:36 UTC, Whoistolu commented on classes/music_album.rb
> +  end
- Well resolved team

2023-12-02 07:37 UTC, Whoistolu commented on spec/author_spec.rb
> +  end
- Well resolved team

2023-12-02 07:44 UTC, Whoistolu commented on schema.sql
> +  FOREIGN KEY (author_id) REFERENCES authors (id)
- Well resolved team

2023-12-02 08:02 UTC, Whoistolu commented on schema.sql
> +);
- Well resolved team

2023-12-02 08:17 UTC, Whoistolu approved these changes
### Hi Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-02 08:30 UTC, merged